- hosts: all
  become: true

  tasks:
    - name: init
      command: "{{ item }}"
      with_items:
        - "apt update"
        - "apt install -y python3"
        - "apt install -y python3-pip"
        - "pip3 install flask"
