- hosts: all
  vars:
    web_model : "https://ywj-horovod.s3.ap-northeast-2.amazonaws.com/torchmodels/model.pt"
    model : "/tmp/init_model.pt"

  tasks:
    - name: delete before train.py
      shell: "rm /tmp/train.py"
      ignore_errors: True

    - name: copy python script
      copy:
        src: "../train.py"
        dest: "/tmp/train.py"
        owner: ubuntu

    - name: train pytorch model
      shell: python3 /tmp/train.py --web_model {{ web_model }} --model {{ model }} --epoch {{ epoch | int }} --round {{ round | int }} > /tmp/log.txt
